spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aqms}
    username: ${DB_USER:aqms}
    password: bestcoder123
  jpa.hibernate.ddl-auto: validate
  flyway.enabled: true
server.port: ${PORT:8080}
