spring:
  datasource:
    url: jdbc:h2:mem:clinicdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  h2.console.enabled: true
server.port: 8080
notification:
  email:
    enabled: false
  sms:
    enabled: false
